name: build

on:
  push:
    # branches-ignore:
    #   - master
    paths-ignore:
      - '**.md'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Cache Go modules
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: make deps

    - name: Build
      run: make build

    - name: Unit tests
      run: make test
